require('pry-byebug')
require_relative('models/actor.rb')
require_relative('models/movie.rb')
require_relative('models/casting.rb')

actor1 = Actor.new({'first_name' => 'Jeff', 'last_name' => 'Bridges'})
actor2 = Actor.new({'first_name' => 'Julie Ann', 'last_name' => 'Moore'})
actor3 = Actor.new({'first_name' => 'John', 'last_name' => 'Goodman'})
actor4 = Actor.new({'first_name' => 'Steve', 'last_name' => 'Buscemi'})
actor1.save()
actor2.save()
actor3.save()
actor4.save()

movie1 = Movie.new({'title' => 'The Big Lebowski', 'genre' => 'comedy', 'rating' => '9', 'budget' => '3_000_000'})
movie2 = Movie.new({'title' => 'The Vanishing', 'genre' => 'crime drama', 'rating' => '8', 'budget' => '5_000_000'})
movie3 = Movie.new({'title' => 'Arlington Road', 'genre' => 'crime thriller', 'rating' => '8', 'budget' => '6_000_000'})
movie4 = Movie.new({'title' => 'Con Air', 'genre' => 'action', 'rating' => '5', 'budget' => '70_000_000'})
movie5 = Movie.new({'title' => 'Magnolia', 'genre' => 'drama', 'rating' => '8', 'budget' => '10_000_000'})
movie6 = Movie.new({'title' => 'Fallen', 'genre' => 'thriller', 'rating' => '8', 'budget' => '8_000_000'})
movie1.save()
movie2.save()
movie3.save()
movie4.save()
movie5.save()
movie6.save()

casting1 = Casting.new({'movie_id' => movie1.id, 'actor_id' => actor1.id, 'fee' => '400_000'})
casting2 = Casting.new({'movie_id' => movie1.id, 'actor_id' => actor2.id, 'fee' => '450_000'})
casting3 = Casting.new({'movie_id' => movie1.id, 'actor_id' => actor3.id, 'fee' => '500_000'})
casting4 = Casting.new({'movie_id' => movie1.id, 'actor_id' => actor4.id, 'fee' => '450_000'})
casting5 = Casting.new({'movie_id' => movie2.id, 'actor_id' => actor1.id, 'fee' => '600_000'})
casting6 = Casting.new({'movie_id' => movie3.id, 'actor_id' => actor1.id, 'fee' => '650_000'})
casting7 = Casting.new({'movie_id' => movie4.id, 'actor_id' => actor4.id, 'fee' => '700_000'})
casting8 = Casting.new({'movie_id' => movie5.id, 'actor_id' => actor2.id, 'fee' => '1_000_000'})
casting9 = Casting.new({'movie_id' => movie6.id, 'actor_id' => actor3.id, 'fee' => '2_000_000'})
casting1.save()
casting2.save()
casting3.save()
casting4.save()
casting5.save()
casting6.save()
casting7.save()
casting8.save()
casting9.save()

binding.pry
nil
